#!/bin/sh

docker-machine stop default
docker-machine rm -f default
docker-machine create --driver virtualbox default
docker-machine ssh default "tce-load -wi sshfs-fuse && mkdir media"
eval $(docker-machine env default)

FOLDER="$(pwd)"
cd ../docker/containers/templates
sh install.sh || exit 1
cd "$FOLDER"

echo .
echo .
echo .
echo .
echo .
echo Now run
echo .
echo sudo sshfs vasko@192.168.2.10:/mnt/media media -o allow_other -o idmap=user
echo .
echo .
echo .
echo .
echo .

docker-machine ssh default
